export const heroCharacters = [
  {
    id: 1,
    system: "Kim",
    systemImg: "/kim.png",
    nameImg: "/Thieu-Lam-Text.webp",
    gender: "Nam",
    martial: "Chưởng pháp, Quyền pháp",
    feature: "Phòng thủ cao, hỗ trợ đồng đội tốt.",
    miniImg: "/Thieu-Lam-Mini.png",
    fullImg: "/Thieu-Lam.webp",
    specialFrame: "/bg-kim.png",
    specialText: "Kiên cường bất khuất",
  },
  {
    id: 2,
    system: "Kim",
    systemImg: "/kim.png",
    nameImg: "/Thien-Vuong-Text.webp",
    gender: "Nam",
    martial: "Dao pháp, Song dao",
    feature: "Kỹ năng công kích tầm xa, sát thương cao, bảo vệ tốt.",
    miniImg: "/Thien-Vuong-Mini.png",
    fullImg: "/Thien-Vuong.webp",
    specialFrame: "/bg-kim.png",
    specialText: "Kiên, hoàn tình duyên",
  },
  {
    id: 3,
    system: "Mộc",
    systemImg: "/moc.png",
    nameImg: "/Duong-Mon-Text.webp",
    gender: "Nữ",
    martial: "Ám khí, Bẫy",
    feature: "Khống chế diện rộng, tấn công bất ngờ.",
    miniImg: "/Duong-Mon-Mini.png",
    fullImg: "/Duong-Mon.webp",
    specialFrame: "/bg-moc.png",
    specialText: "Ẩn mình xuất quỷ nhập thần",
  },
  {
    id: 4,
    system: "Mộc",
    systemImg: "/moc.png",
    nameImg: "/Ngu-Doc-Text.webp",
    gender: "Nữ",
    martial: "Độc công, Bùa chú",
    feature: "Gây hiệu ứng độc, khống chế lâu dài.",
    miniImg: "/Ngu-Doc-Mini.png",
    fullImg: "/Ngu-Doc.webp",
    specialFrame: "/bg-moc.png",
    specialText: "Độc hành thiên hạ",
  },
  {
    id: 5,
    system: "Thủy",
    systemImg: "/thuy.png",
    nameImg: "/Thuy-Yen-Text.webp",
    gender: "Nữ",
    martial: "Kiếm pháp, Thủy công",
    feature: "Tốc độ cao, né tránh linh hoạt.",
    miniImg: "/Thuy-Yen-Mini.png",
    fullImg: "/Thuy-Yen.webp",
    specialFrame: "/bg-thuy.png",
    specialText: "Nhanh như gió nước",
  },
  {
    id: 6,
    system: "Thủy",
    systemImg: "/thuy.png",
    nameImg: "/Nga-Mi-Text.webp",
    gender: "Nữ",
    martial: "Kiếm pháp, Hỗ trợ",
    feature: "Hồi phục, bảo vệ đồng đội.",
    miniImg: "/Nga-Mi-Mini.png",
    fullImg: "/Nga-Mi.webp",
    specialFrame: "/bg-thuy.png",
    specialText: "Từ bi cứu khổ",
  },
  {
    id: 7,
    system: "Hỏa",
    systemImg: "/hoa.png",
    nameImg: "/Cai-Bang-Text.webp",
    gender: "Nam",
    martial: "Chưởng pháp, Gậy",
    feature: "Sát thương bùng nổ, tấn công liên tục.",
    miniImg: "/Cai-Bang-Mini.png",
    fullImg: "/Cai-Bang.webp",
    specialFrame: "/bg-hoa.png",
    specialText: "Bùng nổ sức mạnh",
  },
  {
    id: 8,
    system: "Hỏa",
    systemImg: "/hoa.png",
    nameImg: "/Thien-Nhan-Text.webp",
    gender: "Nam",
    martial: "Chưởng pháp, Kiếm pháp",
    feature: "Sát thương liên tục, hiệu ứng mạnh.",
    miniImg: "/Thien-Nhan-Mini.png",
    fullImg: "/Thien-Nhan.webp",
    specialFrame: "/bg-hoa.png",
    specialText: "Hiệu ứng mạnh mẽ",
  },
  {
    id: 9,
    system: "Thổ",
    systemImg: "/tho.png",
    nameImg: "/Côn-Lôn-Text.webp",
    gender: "Nam",
    martial: "Kiếm pháp, Chưởng pháp",
    feature: "Phòng thủ cao, chống chịu tốt.",
    miniImg: "/Côn-Lôn-Mini.png",
    fullImg: "/Côn-Lôn.webp",
    specialFrame: "/bg-tho.png",
    specialText: "Bức tường vững chắc",
  },
  {
    id: 10,
    system: "Thổ",
    systemImg: "/tho.png",
    nameImg: "/Vo-Dang-Text.webp",
    gender: "Nam",
    martial: "Kiếm pháp, Quyền pháp",
    feature: "Công thủ toàn diện, cân bằng.",
    miniImg: "/Vo-Dang-Mini.png",
    fullImg: "/Vo-Dang.webp",
    specialFrame: "/bg-tho.png",
    specialText: "Cân bằng tuyệt đối",
  }
];
